DROP DATABASE IF EXISTS `test520`;
DROP DATABASE IF EXISTS `test520_preview`;
DROP DATABASE IF EXISTS `test521`;
DROP DATABASE IF EXISTS `test522`;
DROP DATABASE IF EXISTS `test911`;
DROP DATABASE IF EXISTS `test912`;
DROP DATABASE IF EXISTS `test913`;
CREATE DATABASE IF NOT EXISTS `test911`;