package pro.shushi.pamirs.meta.enumclass;

import pro.shushi.pamirs.meta.annotation.Dict;
import pro.shushi.pamirs.meta.common.enmu.ExpBaseEnum;
import pro.shushi.pamirs.meta.common.enmu.IEnum;

@Dict(dictionary = "error.exceptions", displayName = "错误枚举")
public enum ExpEnumerate implements ExpBaseEnum, IEnum<Integer> {

    SYSTEM_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10010001, "系统异常"),
    BASE_IO_ERROR(ERROR_TYPE.GENERIC_ERROR,10010002,"文件读取异常"),
    BASE_CLASS_NOT_FOUNT_ERROR(ERROR_TYPE.GENERIC_ERROR,10010003,"类配置文件不存在"),
    BASE_CLASS_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010004,"类配置文件错误"),
    BASE_ENUM_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010005, "枚举配置文件错误"),
    BASE_FIELD_TYPE_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010006,"模型字段类型错误"),
    BASE_FIELD_LTTYPE_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010007,"模型字段类型错误"),
    BASE_FIELD_TCTYPE_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010008,"模型字段类型错误"),
    BASE_FIELD_TCTYPE_LTYPE_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010009,"模型字段类型错误"),
    BASE_FIELD_NOT_ENUM_ERROR(ERROR_TYPE.GENERIC_ERROR,10010010,"枚举字段类型错误"),
    BASE_CONVERT_ENUM_ERROR(ERROR_TYPE.GENERIC_ERROR,10010011,"枚举转换错误"),
    BASE_FIELD_NOT_MODEL_ERROR(ERROR_TYPE.GENERIC_ERROR,10010012,"模型字段类型错误"),
    BASE_CONVERT_RELATION_ERROR(ERROR_TYPE.GENERIC_ERROR,10010013,"关系转换错误"),
    BASE_MODULE_VERSION_FORMAT_ERROR(ERROR_TYPE.GENERIC_ERROR,10010014,"模块版本格式错误，请配置大中小三个版本并由点字符隔开"),
    BASE_MODULE_VERSION_NOT_DIGIT_ERROR(ERROR_TYPE.GENERIC_ERROR,10010015,"模块版本格式错误，版本中含有不是数字和小数点的字符"),
    BASE_FIELD_ENUM_CONFIG_ERROR(ERROR_TYPE.GENERIC_ERROR,10010016, "枚举类型配置错误"),
    BASE_MODEL_CLASS_IS_NOT_EXISTS_ERROR(ERROR_TYPE.GENERIC_ERROR,10010017,"模型类型错误"),
    BASE_ENUM_CLASS_IS_NOT_EXISTS_ERROR(ERROR_TYPE.GENERIC_ERROR,10010018,"枚举类型错误"),
    BASE_LTYPE_IS_INVALID_ERROR(ERROR_TYPE.GENERIC_ERROR,10010019,"不支持该类型"),
    BASE_LTYPET_IS_INVALID_ERROR(ERROR_TYPE.GENERIC_ERROR,10010020,"不支持该类型"),
    BASE_CLASS_IS_NOT_EXISTS_ERROR(ERROR_TYPE.GENERIC_ERROR,10010021,"类型错误"),
    BASE_CHECK_MODEL_NAME_ERROR(ERROR_TYPE.GENERIC_ERROR,10010022,"模型名称错误"),
    BASE_CHECK_FIELD_NAME_ERROR(ERROR_TYPE.GENERIC_ERROR,10010023,"字段名称错误"),
    BASE_CHECK_COLUMN_NAME_ERROR(ERROR_TYPE.GENERIC_ERROR,10010024,"列名错误"),
    BASE_CHECK_TABLE_NAME_ERROR(ERROR_TYPE.GENERIC_ERROR,10010025,"表名错误"),
    BASE_CHECK_COMMA_EXPRESSION_ERROR(ERROR_TYPE.GENERIC_ERROR,10010026,"逗号表达式错误"),
    BASE_CHECK_DOT_EXPRESSION_ERROR(ERROR_TYPE.GENERIC_ERROR,10010027,"点表达式错误"),

    ;

    private ERROR_TYPE type;

    private int        code;

    private String     msg;

    ExpEnumerate(ERROR_TYPE type, int code, String msg) {
        this.type = type;
        this.code = code;
        this.msg = msg;
    }

}
