CREATE TABLE IF NOT EXISTS `PAMIRS_DATABASES`(
 `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '#id#ID字段，唯一自增索引',
 `SCHEMA_NAME` varchar(128) unique COMMENT '',
 `DEFAULT_CHARACTER_SET_NAME` varchar(128) COMMENT '',
 `DEFAULT_COLLATION_NAME` varchar(128) COMMENT '',
 `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '#createDate#',
 `WRITE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '#writeDate#',
 `CREATE_UID` bigint(20) DEFAULT NULL COMMENT '#createUid#',
 `WRITE_UID` bigint(20) DEFAULT NULL COMMENT '#writeUid#',
 `is_deleted` bigint(20) DEFAULT '0' COMMENT '#is_deleted#逻辑删除',
 PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT 'database';
