package pro.shushi.pamirs.boot.standard.version;

import com.google.common.collect.Sets;

import java.util.Set;

/**
 * PlatformVersionFilter
 *
 * @author yakir on 2024/07/23 14:00.
 */
public class PlatformVersionFilter {

    private static Set<String> PLARFORM_JAR_SET = Sets.<String>newHashSet(

            "pamirs-meta-annotation",
            "pamirs-meta-common",
            "pamirs-meta-model",
            "pamirs-meta-ui",
            "pamirs-sequence-generator",
            "pamirs-meta-ui-model",

            "pamirs-base-boot",
            "pamirs-base-open",
            "pamirs-base-orm",
            "pamirs-base-standard",
            "pamirs-boot-api",
            "pamirs-boot-ddl",
            "pamirs-boot-dependencies",
            "pamirs-boot-modules",
            "pamirs-boot-open",
            "pamirs-boot-orm",
            "pamirs-boot-rpc",
            "pamirs-boot-standard",
            "pamirs-boot-ui",
            "pamirs-distribution-id",
            "pamirs-meta-ui",
            "pamirs-meta-ui-model",
            "pamirs-sequence-generator",

            "pamirs-apps-api",
            "pamirs-apps-core",
            "pamirs-apps-view",
            "pamirs-auth-compatible",
            "pamirs-auth3-api",
            "pamirs-auth3-core",
            "pamirs-auth3-view",
            "pamirs-boot-ui",
            "pamirs-business-api",
            "pamirs-business-core",
            "pamirs-business-core-base",
            "pamirs-business-view",
            "pamirs-channel-api",
            "pamirs-channel-core",
            "pamirs-core-common",
            "pamirs-data-audit-api",
            "pamirs-data-audit-core",
            "pamirs-eip2-api",
            "pamirs-eip2-core",
            "pamirs-eip2-jdbc",
            "pamirs-eip2-view",
            "pamirs-expression-api",
            "pamirs-expression-core",
            "pamirs-file2-api",
            "pamirs-file2-core",
            "pamirs-international",
            "pamirs-management-center",
            "pamirs-message-api",
            "pamirs-message-core",
            "pamirs-my-center-api",
            "pamirs-my-center-core",
            "pamirs-my-center-view",
            "pamirs-resource-api",
            "pamirs-resource-core",
            "pamirs-sequence",
            "pamirs-sql-record-api",
            "pamirs-sql-record-core",
            "pamirs-sys-setting-api",
            "pamirs-sys-setting-core",
            "pamirs-sys-setting-view",
            "pamirs-third-party-communication-api",
            "pamirs-third-party-communication-core",
            "pamirs-third-party-map-api",
            "pamirs-third-party-map-core",
            "pamirs-translate",
            "pamirs-trigger-api",
            "pamirs-trigger-bridge-tbschedule",
            "pamirs-trigger-core",
            "pamirs-user-api",
            "pamirs-user-core",
            "pamirs-user-core-base",
            "pamirs-user-view",

            "pamirs-framework-common",
            "pamirs-framework-configure",
            "pamirs-connectors-cdn",
            "pamirs-connectors-data",
            "pamirs-connectors-data-api",
            "pamirs-connectors-data-autoconfigure",
            "pamirs-connectors-data-ddl",
            "pamirs-connectors-data-dialect",
            "pamirs-connectors-data-elastic-common",
            "pamirs-connectors-data-elastic-rest",
            "pamirs-connectors-data-event",
            "pamirs-connectors-data-infrastructure",
            "pamirs-connectors-data-tx",
            "pamirs-connectors-data-xa",
            "pamirs-connectors-event",
            "pamirs-connectors-event-kafka",
            "pamirs-connectors-event-rabbitmq",
            "pamirs-connectors-event-rocketmq",
            "pamirs-connectors-zookeeper",
            "pamirs-framework-compare",
            "pamirs-framework-compute",
            "pamirs-framework-configure-annotation",
            "pamirs-framework-configure-db",
            "pamirs-framework-configure-printer",
            "pamirs-framework-faas",
            "pamirs-framework-orm",
            "pamirs-framework-orm-client",
            "pamirs-framework-orm-json",
            "pamirs-framework-orm-xml",
            "pamirs-gateways-graph",
            "pamirs-gateways-graph-java",
            "pamirs-gateways-rsql",

            "pamirs-work-bench-api",
            "pamirs-work-bench-core",
            "pamirs-work-bench-view",
            "pamirs-workflow-api",
            "pamirs-workflow-core",
            "pamirs-metadata-manager",
            "pamirs-designer-metadata-api",
            "pamirs-designer-metadata-core",
            "pamirs-flow-designer-base-api",
            "pamirs-flow-designer-base-core",
            "pamirs-eip-designer-api",
            "pamirs-eip-designer-core",
            "pamirs-eip-designer-view",
            "pamirs-data-designer-api",
            "pamirs-data-designer-core",
            "pamirs-data-visualization-api",
            "pamirs-data-visualization-core",
            "pamirs-dataflow-designer-api",
            "pamirs-dataflow-designer-core",
            "pamirs-designer-common-api",
            "pamirs-designer-common-core",
            "pamirs-model-designer-api",
            "pamirs-model-designer-core",
            "pamirs-model-designer-view",
            "pamirs-ui-designer-api",
            "pamirs-ui-designer-core",
            "pamirs-ui-designer-view",
            "pamirs-ui-designer-widget-biz",
            "pamirs-ui-designer-widget-data",
            "pamirs-workflow-designer-api",
            "pamirs-workflow-designer-core"
    );


    public static boolean contains(String module) {
        return PLARFORM_JAR_SET.contains(module);
    }
}
