package pro.shushi.pamirs.business.core.base.utils;

import java.util.HashSet;
import java.util.Set;

/**
 * ProtectedDomain
 *
 * @author yakir on 2022/09/20 16:00.
 */
public class ProtectedDomain {

    private static final Set<String> domainNames = new HashSet<>();

    static {
        domainNames.add("pamirs");
        domainNames.add("oinone");
        domainNames.add("kunlun");
        domainNames.add("tianshan");
        domainNames.add("about");
        domainNames.add("account");
        domainNames.add("activate");
        domainNames.add("add");
        domainNames.add("admin");
        domainNames.add("administrator");
        domainNames.add("api");
        domainNames.add("app");
        domainNames.add("apps");
        domainNames.add("archive");
        domainNames.add("archives");
        domainNames.add("auth");
        domainNames.add("better");
        domainNames.add("blog");
        domainNames.add("cache");
        domainNames.add("cancel");
        domainNames.add("careers");
        domainNames.add("cart");
        domainNames.add("changelog");
        domainNames.add("checkout");
        domainNames.add("codereview");
        domainNames.add("compare");
        domainNames.add("config");
        domainNames.add("configuration");
        domainNames.add("connect");
        domainNames.add("contact");
        domainNames.add("create");
        domainNames.add("delete");
        domainNames.add("direct_messages");
        domainNames.add("documentation");
        domainNames.add("download");
        domainNames.add("downloads");
        domainNames.add("edit");
        domainNames.add("email");
        domainNames.add("employment");
        domainNames.add("enterprise");
        domainNames.add("facebook");
        domainNames.add("faq");
        domainNames.add("favorites");
        domainNames.add("feed");
        domainNames.add("feedback");
        domainNames.add("feeds");
        domainNames.add("fleet");
        domainNames.add("fleets");
        domainNames.add("follow");
        domainNames.add("followers");
        domainNames.add("following");
        domainNames.add("friend");
        domainNames.add("friends");
        domainNames.add("gist");
        domainNames.add("group");
        domainNames.add("groups");
        domainNames.add("help");
        domainNames.add("home");
        domainNames.add("hosting");
        domainNames.add("hostmaster");
        domainNames.add("idea");
        domainNames.add("ideas");
        domainNames.add("index");
        domainNames.add("info");
        domainNames.add("invitations");
        domainNames.add("invite");
        domainNames.add("is");
        domainNames.add("it");
        domainNames.add("job");
        domainNames.add("jobs");
        domainNames.add("json");
        domainNames.add("language");
        domainNames.add("languages");
        domainNames.add("lists");
        domainNames.add("login");
        domainNames.add("logout");
        domainNames.add("logs");
        domainNames.add("mail");
        domainNames.add("map");
        domainNames.add("maps");
        domainNames.add("mine");
        domainNames.add("mis");
        domainNames.add("news");
        domainNames.add("oauth");
        domainNames.add("oauth_clients");
        domainNames.add("offers");
        domainNames.add("openid");
        domainNames.add("order");
        domainNames.add("orders");
        domainNames.add("organizations");
        domainNames.add("plans");
        domainNames.add("popular");
        domainNames.add("post");
        domainNames.add("postmaster");
        domainNames.add("privacy");
        domainNames.add("projects");
        domainNames.add("put");
        domainNames.add("recruitment");
        domainNames.add("register");
        domainNames.add("remove");
        domainNames.add("replies");
        domainNames.add("root");
        domainNames.add("rss");
        domainNames.add("sales");
        domainNames.add("save");
        domainNames.add("search");
        domainNames.add("security");
        domainNames.add("sessions");
        domainNames.add("settings");
        domainNames.add("shop");
        domainNames.add("signup");
        domainNames.add("sitemap");
        domainNames.add("ssl");
        domainNames.add("ssladmin");
        domainNames.add("ssladministrator");
        domainNames.add("sslwebmaster");
        domainNames.add("status");
        domainNames.add("stories");
        domainNames.add("styleguide");
        domainNames.add("subscribe");
        domainNames.add("subscriptions");
        domainNames.add("support");
        domainNames.add("sysadmin");
        domainNames.add("sysadministrator");
        domainNames.add("terms");
        domainNames.add("tour");
        domainNames.add("translations");
        domainNames.add("trends");
        domainNames.add("twitter");
        domainNames.add("twittr");
        domainNames.add("unfollow");
        domainNames.add("unsubscribe");
        domainNames.add("update");
        domainNames.add("url");
        domainNames.add("user");
        domainNames.add("weather");
        domainNames.add("webmaster");
        domainNames.add("widget");
        domainNames.add("widgets");
        domainNames.add("wiki");
        domainNames.add("ww");
        domainNames.add("www");
        domainNames.add("wwww");
        domainNames.add("xfn");
        domainNames.add("xml");
        domainNames.add("xmpp");
        domainNames.add("yaml");
        domainNames.add("yml");
    }

    public static Boolean contains(String domain) {
        return domainNames.contains(domain);
    }
}
