CREATE TABLE `pamirs_schedule_0` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_3` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_4` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_5` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_6` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_7` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_8` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_9` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_10` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_11` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_12` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';

CREATE TABLE `pamirs_schedule_13` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务参数: 主键Id',
  `technical_name` varchar(256) COMMENT '任务参数: 技术名称',
  `table_num` tinyint(1) NOT NULL COMMENT '控制参数: 数据表number',
  `task_type` varchar(256) NOT NULL COMMENT '任务参数: 任务类型',
  `remark` varchar(512) DEFAULT NULL COMMENT '任务参数: 备注信息',
  `interface_name` varchar(256) NOT NULL COMMENT '函数参数: 接口名称',
  `method_name` varchar(256) NOT NULL COMMENT '函数参数: 方法名称',
  `version` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口版本',
  `group` varchar(256) DEFAULT NULL COMMENT '函数参数: 接口分组',
  `timeout` int(11) DEFAULT '3000' COMMENT '函数参数: 接口调用超时时间',
  `tenant` varchar(128) NOT NULL COMMENT '环境参数: 租户',
  `env` varchar(128) COMMENT '环境参数: 环境',
  `own_sign` varchar(128) COMMENT '环境参数: 所有者标记(隔离环境域)',
  `application` varchar(256) NOT NULL COMMENT '环境参数: 应用名',
  `biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `parent_biz_id` bigint(20) DEFAULT NULL COMMENT '订阅者业务id(取模字段)',
  `biz_code` varchar(256) DEFAULT NULL COMMENT '业务编码',
  `context` longtext COMMENT '任务上下文',
  `limit_execute_number` int(11) DEFAULT NULL COMMENT '策略参数: 最大执行次数',
  `is_cycle` tinyint(1) DEFAULT '0' COMMENT '策略参数: 是否循环任务',
  `period_time_value` int(11) DEFAULT NULL COMMENT '策略参数: 执行周期时间',
  `period_time_unit` tinyint(1) DEFAULT NULL COMMENT '策略参数: 执行周期时间单位',
  `period_time_anchor` tinyint(1) DEFAULT '-1' COMMENT '策略参数: 执行周期时间锚点',
  `limit_retry_number` int(11) DEFAULT '-1' COMMENT '策略参数: 最大重试次数',
  `next_retry_time_value` int(11) DEFAULT '1' COMMENT '策略参数: 下次重试间隔时间',
  `next_retry_time_unit` tinyint(1) DEFAULT '13' COMMENT '策略参数: 下次重试间隔时间单位',
  `execute_number` bigint(20) DEFAULT '0' COMMENT '控制参数: 执行次数',
  `next_execute_time` bigint(20) NOT NULL COMMENT '控制参数: 下次执行时间',
  `last_execute_time` bigint(20) DEFAULT NULL COMMENT '控制参数: 最新执行时间',
  `retry_number` int(11) DEFAULT '0' COMMENT '控制参数: 重试次数',
  `task_status` tinyint(1) DEFAULT '0' COMMENT '控制参数: 任务状态',
  `error_log` longtext COMMENT '控制参数: 异常堆栈信息,注意要控制大小',
  `is_deleted` bigint(20) NOT NULL DEFAULT '0' COMMENT '控制参数: 删除标记',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `write_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`,`is_deleted`),
  KEY `pamirs_schedule_task_type_task_status_next_execute_time` (`task_type`,`task_status`,`next_execute_time`),
  KEY `pamirs_schedule_biz_id` (`biz_id`),
  UNIQUE KEY `pamirs_schedule_technical_name` (`technical_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COMMENT='任务分发表';