package pro.shushi.pamirs.meta.dsl.enumeration;

import pro.shushi.pamirs.meta.annotation.Errors;
import pro.shushi.pamirs.meta.common.enmu.ExpBaseEnum;
import pro.shushi.pamirs.meta.common.enmu.IEnum;


@Errors(displayName = "DSL错误枚举")
public enum DslExpEnumerate implements ExpBaseEnum, IEnum<Integer> {

    SYSTEM_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020001, "系统异常"),
    BASE_ACTION_PARAMS_IS_EMPTY_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020002, "动作入参为空"),
    BASE_ACTION_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020003, "动作执行异常"),
    BASE_COPY_DATA_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020004, "必须同为集合，才能进行数据拷贝"),
    BASE_END_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020005, "返回执行异常"),
    BASE_EXTD_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020006, "扩展点执行异常"),
    BASE_FUNC_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020007, "函数执行异常"),
    BASE_FOREACH_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020008, "循环执行异常"),
    BASE_FOREACH_PARAMS_IS_EMPTY_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020009, "循环执行异常"),
    BASE_FOREACH_PARAMS_IS_NOT_COLLECTION_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020010, "循环执行异常"),
    BASE_FOREACH_PARAMS_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020011, "循环执行异常"),
    BASE_TRANSFORM_NODE_ID_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020012, "逻辑转换异常"),
    BASE_TRANSFORM_NODE_IF_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020013, "条件转换异常"),
    BASE_TRANSFORM_NODE_IF_BRANCH_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020014, "条件转换异常"),
    BASE_TRANSFORM_NODE_FOR_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020015, "循环转换异常"),
    BASE_TRANSFORM_NODE_FOR_BRANCH_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020016, "循环转换异常"),
    BASE_TRANSFORM_NODE_TO_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020017, "跳转转换异常"),
    BASE_TRANSFORM_NODE_TO_CHECK_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020018, "跳转配置错误"),
    BASE_TRANSFORM_NODE_TO_IS_NOT_EXISTS_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020019, "跳转配置错误"),
    BASE_TRANSFORM_NODE_FOR_END_IS_NOT_EXISTS_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020020, "循环配置错误"),
    BASE_TRANSFORM_NODE_IF_NO_BRANCH_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020020, "条件转换配置错误"),
    BASE_TRANSFORM_NODE_TO_ID_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020021, "跳转配置错误"),
    BASE_TRANSFORM_NODE_TO_PRE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020022, "跳转配置错误"),
    BASE_MACHINE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020023, "状态机配置错误"),
    BASE_OBJ_PARAMS_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020024, "对象操作入参错误"),
    BASE_OBJ_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020025, "对象操作异常"),
    BASE_READ_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020026, "读操作异常"),
    BASE_READ_RSQL_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020027, "读操作异常"),
    BASE_START_HANDLE_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020028, "开始节点异常"),
    BASE_UNSUPPORTED_ENCODING_ERROR(ERROR_TYPE.SYSTEM_ERROR, 10020029, "不支持的编码格式"),

    ;

    private ERROR_TYPE type;

    private int code;

    private String msg;

    DslExpEnumerate(ERROR_TYPE type, int code, String msg) {
        this.type = type;
        this.code = code;
        this.msg = msg;
    }

}
